site_name: Programmers Guide
site_url: http://cocos2d-x.org/programmersguide
site_description: The Cocos2d-x Programmers Guide
site_description: The Cocos2d-x Programmers Guide
site_author: The Cocos2d-x Team
pages:
- Home: 'index.md'
- Contents:
    - 'Cocos': 'cocos.md'
    - 'Chapters':
      - '1: About Cocos2d-x': '1.md'
      - '2: Basic Concepts': '2.md'
      - '3: Sprites': '3.md'
      - '4: Actions': '4.md'
      - '5: Scenes': '5.md'
      - '6: UI': '6.md'
      - '7: Other Node Types': '7.md'
      - '8: Event Dispatch': '8.md'
      - '9: 3D': '9.md'
      - '10: Scripting': '10.md'
      - '11: Services': '11.md'
      - '12: Physics': '12.md'
      - '13: Audio': '13.md'
      - '14: Advanced Topics': '14.md'
    - 'Appendices':
      - 'A: Prerequisites': 'A.md'
      - 'B: Android (Terminal) Setup': 'B.md'
      - 'C: Android (Eclipse) Setup': 'C.md'
      - 'D: iOS Setup': 'D.md'
      - 'E: Mac OSX Setup': 'E.md'
      - 'F: Linux Setup': 'F.md'
      - 'G: Windows Setup': 'G.md'
      - 'H: Windows Phone Setup': 'H.md'
      - 'I: SDKBOX': 'I.md'
- About: 'title.md'

#theme: readable
theme_dir: 'theme'
copyright: Copyright &copy; 2014-2016, Chukong Technology
use_directory_urls: false
repo_url: https://github.com/chukong/programmers-guide
repo_name: GitHub
google_analytics: ['UA-3216502-3', 'cocos2d-x.org']
